name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 
  - numpy=1.23.4
  - protobuf=3.20.0
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.13.3